
package com.tiilii.resource.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IResourceService", targetNamespace = "http://soap.service.resource.tiilii.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IResourceService {


    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTextbookStructureByParentUid", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTextbookStructureByParentUid")
    @ResponseWrapper(localName = "selectTextbookStructureByParentUidResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTextbookStructureByParentUidResponse")
    public String selectTextbookStructureByParentUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTopicsForTest", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicsForTest")
    @ResponseWrapper(localName = "selectTopicsForTestResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicsForTestResponse")
    public String selectTopicsForTest(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectVideos", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectVideos")
    @ResponseWrapper(localName = "selectVideosResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectVideosResponse")
    public String selectVideos(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTextbookStructureSection", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTextbookStructureSection")
    @ResponseWrapper(localName = "selectTextbookStructureSectionResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTextbookStructureSectionResponse")
    public String selectTextbookStructureSection(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTopicStats", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicStats")
    @ResponseWrapper(localName = "selectTopicStatsResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicStatsResponse")
    public String selectTopicStats(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertTextbookStructure", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertTextbookStructure")
    @ResponseWrapper(localName = "insertTextbookStructureResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertTextbookStructureResponse")
    public String insertTextbookStructure(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateTopic", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.UpdateTopic")
    @ResponseWrapper(localName = "updateTopicResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.UpdateTopicResponse")
    public String updateTopic(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTopics", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopics")
    @ResponseWrapper(localName = "selectTopicsResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicsResponse")
    public String selectTopics(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTopicForCheck", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicForCheck")
    @ResponseWrapper(localName = "selectTopicForCheckResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicForCheckResponse")
    public String selectTopicForCheck(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectResourceTags", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectResourceTags")
    @ResponseWrapper(localName = "selectResourceTagsResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectResourceTagsResponse")
    public String selectResourceTags(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertTopic", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertTopic")
    @ResponseWrapper(localName = "insertTopicResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertTopicResponse")
    public String insertTopic(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTextbookStructures", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.DeleteTextbookStructures")
    @ResponseWrapper(localName = "deleteTextbookStructuresResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.DeleteTextbookStructuresResponse")
    public String deleteTextbookStructures(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectVideoByParentUid", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectVideoByParentUid")
    @ResponseWrapper(localName = "selectVideoByParentUidResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectVideoByParentUidResponse")
    public String selectVideoByParentUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateVideo", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.UpdateVideo")
    @ResponseWrapper(localName = "updateVideoResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.UpdateVideoResponse")
    public String updateVideo(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTextbookStructureByUid", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTextbookStructureByUid")
    @ResponseWrapper(localName = "selectTextbookStructureByUidResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTextbookStructureByUidResponse")
    public String selectTextbookStructureByUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertTextbook", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertTextbook")
    @ResponseWrapper(localName = "insertTextbookResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertTextbookResponse")
    public String insertTextbook(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectStructureTreeByTextbookStructureUid", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectStructureTreeByTextbookStructureUid")
    @ResponseWrapper(localName = "selectStructureTreeByTextbookStructureUidResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectStructureTreeByTextbookStructureUidResponse")
    public String selectStructureTreeByTextbookStructureUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afterCheckVideo", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.AfterCheckVideo")
    @ResponseWrapper(localName = "afterCheckVideoResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.AfterCheckVideoResponse")
    public String afterCheckVideo(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectCourseByUid", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectCourseByUid")
    @ResponseWrapper(localName = "selectCourseByUidResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectCourseByUidResponse")
    public String selectCourseByUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTextbookByUid", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.DeleteTextbookByUid")
    @ResponseWrapper(localName = "deleteTextbookByUidResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.DeleteTextbookByUidResponse")
    public String deleteTextbookByUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertResourceTag", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertResourceTag")
    @ResponseWrapper(localName = "insertResourceTagResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertResourceTagResponse")
    public String insertResourceTag(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectVideoForCheck", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectVideoForCheck")
    @ResponseWrapper(localName = "selectVideoForCheckResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectVideoForCheckResponse")
    public String selectVideoForCheck(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTopicForReCheck", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicForReCheck")
    @ResponseWrapper(localName = "selectTopicForReCheckResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicForReCheckResponse")
    public String selectTopicForReCheck(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectNodeTree", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectNodeTree")
    @ResponseWrapper(localName = "selectNodeTreeResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectNodeTreeResponse")
    public String selectNodeTree(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bindOrUnbindTextbookKnowitem", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.BindOrUnbindTextbookKnowitem")
    @ResponseWrapper(localName = "bindOrUnbindTextbookKnowitemResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.BindOrUnbindTextbookKnowitemResponse")
    public String bindOrUnbindTextbookKnowitem(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateTextbook", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.UpdateTextbook")
    @ResponseWrapper(localName = "updateTextbookResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.UpdateTextbookResponse")
    public String updateTextbook(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTextbooks", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTextbooks")
    @ResponseWrapper(localName = "selectTextbooksResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTextbooksResponse")
    public String selectTextbooks(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bindOrUnbindNodeKnowitem", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.BindOrUnbindNodeKnowitem")
    @ResponseWrapper(localName = "bindOrUnbindNodeKnowitemResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.BindOrUnbindNodeKnowitemResponse")
    public String bindOrUnbindNodeKnowitem(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertCourse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertCourse")
    @ResponseWrapper(localName = "insertCourseResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertCourseResponse")
    public String insertCourse(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTopicsByLimit", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicsByLimit")
    @ResponseWrapper(localName = "selectTopicsByLimitResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicsByLimitResponse")
    public String selectTopicsByLimit(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertTopicBackUp", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertTopicBackUp")
    @ResponseWrapper(localName = "insertTopicBackUpResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertTopicBackUpResponse")
    public String insertTopicBackUp(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectLogResourceActions", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectLogResourceActions")
    @ResponseWrapper(localName = "selectLogResourceActionsResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectLogResourceActionsResponse")
    public String selectLogResourceActions(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afterCheckTopic", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.AfterCheckTopic")
    @ResponseWrapper(localName = "afterCheckTopicResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.AfterCheckTopicResponse")
    public String afterCheckTopic(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertVideos", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertVideos")
    @ResponseWrapper(localName = "insertVideosResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertVideosResponse")
    public String insertVideos(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertVideo", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertVideo")
    @ResponseWrapper(localName = "insertVideoResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.InsertVideoResponse")
    public String insertVideo(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTopicByUid", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicByUid")
    @ResponseWrapper(localName = "selectTopicByUidResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicByUidResponse")
    public String selectTopicByUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateTextbookStructure", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.UpdateTextbookStructure")
    @ResponseWrapper(localName = "updateTextbookStructureResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.UpdateTextbookStructureResponse")
    public String updateTextbookStructure(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSystemTime", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.GetSystemTime")
    @ResponseWrapper(localName = "getSystemTimeResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.GetSystemTimeResponse")
    public String getSystemTime();

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTextbookStructureChapter", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTextbookStructureChapter")
    @ResponseWrapper(localName = "selectTextbookStructureChapterResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTextbookStructureChapterResponse")
    public String selectTextbookStructureChapter(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afterUseTopic", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.AfterUseTopic")
    @ResponseWrapper(localName = "afterUseTopicResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.AfterUseTopicResponse")
    public String afterUseTopic(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTextbookByUid", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTextbookByUid")
    @ResponseWrapper(localName = "selectTextbookByUidResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTextbookByUidResponse")
    public String selectTextbookByUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTopicCheckAndRecheckInfoByUid", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicCheckAndRecheckInfoByUid")
    @ResponseWrapper(localName = "selectTopicCheckAndRecheckInfoByUidResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicCheckAndRecheckInfoByUidResponse")
    public String selectTopicCheckAndRecheckInfoByUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTopicBackUps", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicBackUps")
    @ResponseWrapper(localName = "selectTopicBackUpsResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectTopicBackUpsResponse")
    public String selectTopicBackUps(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectKnowitems", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectKnowitems")
    @ResponseWrapper(localName = "selectKnowitemsResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectKnowitemsResponse")
    public String selectKnowitems(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectIPublishers", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectIPublishers")
    @ResponseWrapper(localName = "selectIPublishersResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectIPublishersResponse")
    public String selectIPublishers(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afterReCheckTopic", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.AfterReCheckTopic")
    @ResponseWrapper(localName = "afterReCheckTopicResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.AfterReCheckTopicResponse")
    public String afterReCheckTopic(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectCourses", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectCourses")
    @ResponseWrapper(localName = "selectCoursesResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectCoursesResponse")
    public String selectCourses(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCourse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.UpdateCourse")
    @ResponseWrapper(localName = "updateCourseResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.UpdateCourseResponse")
    public String updateCourse(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectVideoByUid", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectVideoByUid")
    @ResponseWrapper(localName = "selectVideoByUidResponse", targetNamespace = "http://soap.service.resource.tiilii.com/", className = "com.tiilii.resource.service.soap.SelectVideoByUidResponse")
    public String selectVideoByUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData);

}
