
package com.tiilii.resource.service.soap;

import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.apache.log4j.Logger;

import com.tiilii.config.WebServiceWSDLConstants;
import com.tiilii.util.ConfigPropertiesUtil;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ResourceServiceService", targetNamespace = "http://soap.service.resource.tiilii.com/")
public class ResourceServiceService
    extends Service
{

    private final static URL RESOURCESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException RESOURCESERVICESERVICE_EXCEPTION;
    private final static QName RESOURCESERVICESERVICE_QNAME = new QName("http://soap.service.resource.tiilii.com/", "ResourceServiceService");

    private static Logger logger = Logger.getLogger(ResourceServiceService.class);
    static {
        URL url = null;
        WebServiceException e = null;
        String wsdl = null;
        try {
        	wsdl = (String) ConfigPropertiesUtil.proName("wsdl.properties").getProperty("resource_wsdl");
            url = new URL(wsdl);
            logger.info("--------------resource wsdl: " + wsdl);
        } catch (MalformedURLException | UnsupportedEncodingException ex) {
            e = new WebServiceException(ex);
        }
        RESOURCESERVICESERVICE_WSDL_LOCATION = url;
        RESOURCESERVICESERVICE_EXCEPTION = e;
    }

    public ResourceServiceService() {
        super(__getWsdlLocation(), RESOURCESERVICESERVICE_QNAME);
    }

    public ResourceServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESOURCESERVICESERVICE_QNAME, features);
    }

    public ResourceServiceService(URL wsdlLocation) {
        super(wsdlLocation, RESOURCESERVICESERVICE_QNAME);
    }

    public ResourceServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESOURCESERVICESERVICE_QNAME, features);
    }

    public ResourceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResourceServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IResourceService
     */
    @WebEndpoint(name = "ResourceServicePort")
    public IResourceService getResourceServicePort() {
        return super.getPort(new QName("http://soap.service.resource.tiilii.com/", "ResourceServicePort"), IResourceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IResourceService
     */
    @WebEndpoint(name = "ResourceServicePort")
    public IResourceService getResourceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service.resource.tiilii.com/", "ResourceServicePort"), IResourceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESOURCESERVICESERVICE_EXCEPTION!= null) {
            throw RESOURCESERVICESERVICE_EXCEPTION;
        }
        return RESOURCESERVICESERVICE_WSDL_LOCATION;
    }

}
