
package com.tiilii.sso.wsservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISSOService", targetNamespace = "http://wsService.sso.tiilii.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISSOService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ssoCheckUserLoginId", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoCheckUserLoginId")
    @ResponseWrapper(localName = "ssoCheckUserLoginIdResponse", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoCheckUserLoginIdResponse")
    public String ssoCheckUserLoginId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ssoLogin", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoLogin")
    @ResponseWrapper(localName = "ssoLoginResponse", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoLoginResponse")
    public String ssoLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ssoNewUserLogin", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoNewUserLogin")
    @ResponseWrapper(localName = "ssoNewUserLoginResponse", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoNewUserLoginResponse")
    public String ssoNewUserLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ssoNewUser", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoNewUser")
    @ResponseWrapper(localName = "ssoNewUserResponse", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoNewUserResponse")
    public String ssoNewUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ssoSelectUserInfo", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoSelectUserInfo")
    @ResponseWrapper(localName = "ssoSelectUserInfoResponse", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoSelectUserInfoResponse")
    public String ssoSelectUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ssoDeleteUserLogin", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoDeleteUserLogin")
    @ResponseWrapper(localName = "ssoDeleteUserLoginResponse", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoDeleteUserLoginResponse")
    public String ssoDeleteUserLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ssoUpdateUserInfo", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoUpdateUserInfo")
    @ResponseWrapper(localName = "ssoUpdateUserInfoResponse", targetNamespace = "http://wsService.sso.tiilii.com/", className = "com.tiilii.sso.wsservice.SsoUpdateUserInfoResponse")
    public String ssoUpdateUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
