
package com.tiilii.message.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * My portType description
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMessageService", targetNamespace = "http://soap.service.message.tiilii.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMessageService {


    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectChatList", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectChatList")
    @ResponseWrapper(localName = "selectChatListResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectChatListResponse")
    public String selectChatList(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectMessageBySenderUserUid", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectMessageBySenderUserUid")
    @ResponseWrapper(localName = "selectMessageBySenderUserUidResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectMessageBySenderUserUidResponse")
    public String selectMessageBySenderUserUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectNoticeByUid", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectNoticeByUid")
    @ResponseWrapper(localName = "selectNoticeByUidResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectNoticeByUidResponse")
    public String selectNoticeByUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectMessageBy2UserUid", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectMessageBy2UserUid")
    @ResponseWrapper(localName = "selectMessageBy2UserUidResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectMessageBy2UserUidResponse")
    public String selectMessageBy2UserUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteMessageBySenderUserUid", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.DeleteMessageBySenderUserUid")
    @ResponseWrapper(localName = "deleteMessageBySenderUserUidResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.DeleteMessageBySenderUserUidResponse")
    public String deleteMessageBySenderUserUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "flagReadMessage", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.FlagReadMessage")
    @ResponseWrapper(localName = "flagReadMessageResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.FlagReadMessageResponse")
    public String flagReadMessage(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMomentsList", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.GetMomentsList")
    @ResponseWrapper(localName = "getMomentsListResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.GetMomentsListResponse")
    public String getMomentsList(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectMessageUnReadCount", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectMessageUnReadCount")
    @ResponseWrapper(localName = "selectMessageUnReadCountResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectMessageUnReadCountResponse")
    public String selectMessageUnReadCount(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDataStatistics", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.GetDataStatistics")
    @ResponseWrapper(localName = "getDataStatisticsResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.GetDataStatisticsResponse")
    public String getDataStatistics(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectMessageByMessageUid", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectMessageByMessageUid")
    @ResponseWrapper(localName = "selectMessageByMessageUidResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectMessageByMessageUidResponse")
    public String selectMessageByMessageUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertNotice", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.InsertNotice")
    @ResponseWrapper(localName = "insertNoticeResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.InsertNoticeResponse")
    public String insertNotice(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectContractsMember", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectContractsMember")
    @ResponseWrapper(localName = "selectContractsMemberResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectContractsMemberResponse")
    public String selectContractsMember(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectNotices", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectNotices")
    @ResponseWrapper(localName = "selectNoticesResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectNoticesResponse")
    public String selectNotices(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SendEmailResponse")
    public String sendEmail(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendSMS", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SendSMS")
    @ResponseWrapper(localName = "sendSMSResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SendSMSResponse")
    public String sendSMS(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteMessageByReceiverUserUid", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.DeleteMessageByReceiverUserUid")
    @ResponseWrapper(localName = "deleteMessageByReceiverUserUidResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.DeleteMessageByReceiverUserUidResponse")
    public String deleteMessageByReceiverUserUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteNotices", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.DeleteNotices")
    @ResponseWrapper(localName = "deleteNoticesResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.DeleteNoticesResponse")
    public String deleteNotices(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "revokeMessage", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.RevokeMessage")
    @ResponseWrapper(localName = "revokeMessageResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.RevokeMessageResponse")
    public String revokeMessage(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectMessageByReceiverUserUid", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectMessageByReceiverUserUid")
    @ResponseWrapper(localName = "selectMessageByReceiverUserUidResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectMessageByReceiverUserUidResponse")
    public String selectMessageByReceiverUserUid(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertMessage", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.InsertMessage")
    @ResponseWrapper(localName = "insertMessageResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.InsertMessageResponse")
    public String insertMessage(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

    /**
     * 
     * @param xmlData
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectChatRecord", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectChatRecord")
    @ResponseWrapper(localName = "selectChatRecordResponse", targetNamespace = "http://soap.service.message.tiilii.com/", className = "com.tiilii.message.service.soap.SelectChatRecordResponse")
    public String selectChatRecord(
        @WebParam(name = "XmlData", targetNamespace = "")
        String xmlData)
        throws Exception_Exception
    ;

}
