
package com.tiilii.fs.ws;

import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.apache.log4j.Logger;

import com.tiilii.util.ConfigPropertiesUtil;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FSServiceImplService", targetNamespace = "http://ws.fs.tiilii.com/")
public class FSServiceImplService
    extends Service
{

    private final static URL FSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName FSSERVICEIMPLSERVICE_QNAME = new QName("http://ws.fs.tiilii.com/", "FSServiceImplService");
    private static Logger logger = Logger.getLogger(FSServiceImplService.class);
    static {
        URL url = null;
        WebServiceException e = null;
        String wsdl = null;
        try {
        	wsdl = (String) ConfigPropertiesUtil.proName("wsdl.properties").getProperty("fs_wsdl");
            url = new URL(wsdl);
            logger.info("--------------fs wsdl: " + wsdl);
        } catch (MalformedURLException | UnsupportedEncodingException ex) {
            e = new WebServiceException(ex);
        } 
        FSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        FSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public FSServiceImplService() {
        super(__getWsdlLocation(), FSSERVICEIMPLSERVICE_QNAME);
    }

    public FSServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FSSERVICEIMPLSERVICE_QNAME, features);
    }

    public FSServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, FSSERVICEIMPLSERVICE_QNAME);
    }

    public FSServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FSSERVICEIMPLSERVICE_QNAME, features);
    }

    public FSServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FSServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IFSService
     */
    @WebEndpoint(name = "FSServiceImplPort")
    public IFSService getFSServiceImplPort() {
        return super.getPort(new QName("http://ws.fs.tiilii.com/", "FSServiceImplPort"), IFSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFSService
     */
    @WebEndpoint(name = "FSServiceImplPort")
    public IFSService getFSServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.fs.tiilii.com/", "FSServiceImplPort"), IFSService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw FSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return FSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
